theme: jekyll-theme-minimal
title: Jon Debonis
description: homepage
url: https://www.jondebonis.com
author: jondebonis
twitter:
  username: jondebonis
  card: summary
logo: /assets/logo.jpg
social:
  name: Jon Debonis
  links:
    - https://twitter.com/jondebonis
    - https://www.linkedin.com/in/jondebonis
    - https://github.com/jondb
    - https://keybase.io/jondb
google_analytics: UA-127465278-1


